on:
  push:
  pull_request:
    branches:
      - master

name: create-document

jobs:
  R-CMD-check:
    container: alanocallaghan/bocker:0.1.0
    runs-on: ${{ matrix.config.os }} # we run many different builds
    strategy:
      # just an example matrix
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Render document
        run: |
          rmarkdown::render('Workflow.Rmd')
        shell: Rscript {0}
